### ISSUE TITLE
Build phone against vanilla Linux

### ISSUE THREAD

**Issue by jeremiah** [PDXostc/phone#5]
Hi,

Firstly, thanks for your work on phone!

It looks like you're building phone against Tizen, probably because you're depending on things like Crosswalk. But I would think that being able to build against vanilla GNU/Linux will bring you more users and therefor more bug reports, better quality, more contributions, etc.

If you're willing to consider building against vanilla linux, I'm happy to test phone on my system for example and help with porting if needed.

Thanks

**Comment by amcgee7** [comment]
Hi, jeremiah

Yes phone is a Tizen web app.  It uses a tizen extension on crosswalk to talk with ofono.   It will make and receive calls.  It has a direct dependency on the Tizen object so to make it work on other linux distros you would have to have those pieces rebuilt. 

Thanks, 

Art McGee

**Comment by jeremiah** [comment]
Wouldn't it be a better approach to eliminate as many dependencies as possible to make your software portable? Right now you're dependent on an OS that might disappear.

**Comment by amcgee7** [comment]
Jeremiah,

Thanks for your input.  It's a business objective so changing the OS is not
an option.  It's supposed to be a tizen web app that pairs with and does
calling from your phone.  ofono works at the native layer and provides most
the functionality.  If your looking at something more portable I'd look at
that.

https://01.org/ofono

On 10 April 2015 at 00:30, Jeremiah C. Foster notifications@github.com
wrote:

> Wouldn't it be a better approach to eliminate as many dependencies as
> possible to make your software portable? Right now you're dependent on an
> OS that might disappear.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PDXostc/phone/issues/5#issuecomment-91464691.

## 

_Art McGee_
Infotainment Engineer

Jaguar Land Rover North America, LLC
1419 NW 14th Ave, Portland, Oregon, 97209
JaguarUSA.com http://www.jaguarusa.com/index.html  |  LandRoverUSA.com
http://www.landrover.com/us/en/lr/
